/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comunicacion_socket;

/**
 *
 * @author adrian.jimenez
 */
public class Int_datos extends javax.swing.JFrame {

    /**
     * Creates new form Int_datos
     */
    public Int_datos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public String caputarar_ip(){
        String ip3=ip.getText().toString();
        return ip3;
        
        }
     
     public int caputarar_puerto(){
     String port_string=puerto.getText().toString();
     int port3=Integer.parseInt(port_string);
     return port3;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        port_text = new javax.swing.JLabel();
        puerto = new javax.swing.JTextField();
        ip_text = new javax.swing.JLabel();
        ip = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ip_text1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pregunton!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        port_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        port_text.setForeground(new java.awt.Color(255, 255, 255));
        port_text.setText("Puerto de acceso");
        getContentPane().add(port_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoActionPerformed(evt);
            }
        });
        getContentPane().add(puerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 122, -1));

        ip_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ip_text.setForeground(new java.awt.Color(255, 255, 255));
        ip_text.setText("Ip del servidor");
        getContentPane().add(ip_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        getContentPane().add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 183, -1));

        btn1.setBackground(new java.awt.Color(204, 255, 204));
        btn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comunicacion_socket/ok.png"))); // NOI18N
        btn1.setText("Aceptar");
        btn1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, 40));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 55)); // NOI18N
        jLabel2.setText("Preguntón!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 360, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comunicacion_socket/gradient-wallpaper-18.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 290));

        ip_text1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ip_text1.setForeground(new java.awt.Color(255, 255, 255));
        ip_text1.setText("Ip del servidor");
        getContentPane().add(ip_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       
        if(!ip.getText().equals(null)&& (!puerto.getText().equals(null))){
        this.setVisible(false);
        int pregf=0;
        int pregw=0;
        
        String[] b4=new String[7];
        String ip2=ip.getText().toString();
        String port_string=puerto.getText().toString();
        int port=Integer.parseInt(port_string);
        
        Cliente cli=new Cliente(port,ip2);
        
        b4=cli.Iniciar();
        
        
        Interfaz_Preguntas intit=new Interfaz_Preguntas();  
        intit.Interfaz_Preguntas(port, ip2,pregf,pregw);
        intit.AsignarPreg(b4);
        
        }
        
       

        

// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Int_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Int_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Int_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Int_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Int_datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JTextField ip;
    private javax.swing.JLabel ip_text;
    private javax.swing.JLabel ip_text1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel port_text;
    private javax.swing.JTextField puerto;
    // End of variables declaration//GEN-END:variables
}
